# -*- coding: utf-8 -*-
"""欢迎使用 Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

scores = input().split()

fail_count = 0
count = 0
total = 0

# 转换成整数列表
nums = []

for s in scores:
    score = int(s)
    nums.append(score)

    if score < 60:
        fail_count += 1

    count += 1
    total += score

# 输出不及格人数
print(fail_count)

# 最大最小平均
maximum1 = max(nums)
minimum2 = min(nums)
average = total / count

print(f"平均分:{average}")
print(f"最高分:{maximum1}")
print(f"最低分:{minimum2}")